### ISSUE TITLE
multiple bug when enumeration

### ISSUE THREAD

**Issue by pzam0101** [qtc-de/remote-method-guesser#73]
hi , when i enum some target i get some error  

` java -jar ./rmg enum TARGET  1099`

`[-] Caught unexpected java.rmi.UnmarshalException during list call.
[-] Please report this to improve rmg :)
[-] StackTrace:
java.rmi.UnmarshalException: Transport return code invalid
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:246)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:380)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.list(RegistryImpl_Stub.java:91)
	at eu.tneitzel.rmg.networking.RMIRegistryEndpoint.getBoundNames(RMIRegistryEndpoint.java:116)
	at eu.tneitzel.rmg.operations.Dispatcher.obtainBoundNames(Dispatcher.java:84)
	at eu.tneitzel.rmg.operations.Dispatcher.dispatchEnum(Dispatcher.java:588)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at eu.tneitzel.rmg.operations.Operation.invoke(Operation.java:385)
	at eu.tneitzel.rmg.Starter.main(Starter.java:41)
[-] Cannot continue from here.`

or 

`java -jar ./rmg enum TARGET 1099`

`[-] Caught unexpected java.rmi.UnmarshalException during list call.
[-] Please report this to improve rmg :)
[-] StackTrace:
java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is: 
	java.io.EOFException
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:254)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:380)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.list(RegistryImpl_Stub.java:91)
	at eu.tneitzel.rmg.networking.RMIRegistryEndpoint.getBoundNames(RMIRegistryEndpoint.java:116)
	at eu.tneitzel.rmg.operations.Dispatcher.obtainBoundNames(Dispatcher.java:84)
	at eu.tneitzel.rmg.operations.Dispatcher.dispatchEnum(Dispatcher.java:588)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at eu.tneitzel.rmg.operations.Operation.invoke(Operation.java:385)
	at eu.tneitzel.rmg.Starter.main(Starter.java:41)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:240)
	... 11 more
[-] Cannot continue from here.`

**Comment by qtc-de** [comment]
Hi @pzam0101 :wave: 

thanks for reporting :+1: Do you have some more information about the target? Are other tools (like e.g. nmap or metasploit) capable of listing the bound names?

`rmg` messes a lot with Java RMI internals and `StreamCorruption` or `EOF` errors have been encountered (and hopefully been fixed) in the past. These are kind of expected, as `rmg` uses the RMI protocol in *unusual ways*. Your issue, however, is caused by the `RegistryImpl_Stub.list` method. This is an internal Java RMI method that does not get modified by `rmg`. Therefore, other tools should also fail and the bug lies probably in the RMI server itself instead within the client tooling.

If I had to guess, I would say that the server probably uses a custom socket factory that performs some additional modifications to the transmitted RMI data. This is rare, but some developers do this. In such situations, you need the servers socket factory implementation to communicate with the registry. But without further information it is hard to tell :shrug:

**Comment by pzam0101** [comment]
yes, your guess is somehow true, in the flow of the network have multiple  DPI(Deep packet Inspection) that manipulate the packet and cause this error, i used a proxy and it's resolved ;) 

thanks for your help and create these interesting  tools

**Comment by qtc-de** [comment]
Cool :sunglasses: Glad your issue has been resolved :+1:
